# Generated by Django 2.0.7 on 2018-07-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=20)),
                ('device_type', models.CharField(max_length=7)),
                ('status', models.CharField(max_length=7)),
                ('date', models.DateTimeField(verbose_name='date of Occurance')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of Occurance')),
                ('offline_count_by_day', models.IntegerField(default=0)),
                ('online_count_by_day', models.IntegerField(default=0)),
            ],
        ),
    ]
