# Generated by Django 2.0.7 on 2018-07-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurance',
            name='date',
        ),
        migrations.AddField(
            model_name='occurance',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='occurance',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='occurance',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
