# Generated by Django 2.0.7 on 2018-07-12 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter_app', '0002_auto_20180712_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurance',
            name='day',
        ),
        migrations.RemoveField(
            model_name='occurance',
            name='month',
        ),
        migrations.RemoveField(
            model_name='occurance',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='occurance',
            name='year',
        ),
        migrations.AddField(
            model_name='occurance',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2001, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summarybyday',
            name='date',
            field=models.DateField(),
        ),
    ]
