# Generated by Django 2.0.7 on 2018-07-13 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter_app', '0003_auto_20180712_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurance',
            name='datetime',
        ),
        migrations.AddField(
            model_name='occurance',
            name='date',
            field=models.DateField(default=datetime.date(2001, 1, 1)),
            preserve_default=False,
        ),
    ]
